import { jsPDF } from "jspdf";
import type { Message } from "../drizzle/schema";

interface ConversationData {
  title: string;
  createdAt: Date;
  sentinelName?: string;
  modelName?: string;
  totalTokens?: number;
  totalCost?: number;
  messages: Message[];
}

/**
 * Generate a formatted PDF document from a conversation
 */
export async function generateConversationPDF(data: ConversationData): Promise<Buffer> {
  // Create new PDF document (A4 size)
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - 2 * margin;
  let yPosition = margin;

  // Helper function to add new page if needed
  const checkPageBreak = (requiredSpace: number) => {
    if (yPosition + requiredSpace > pageHeight - margin) {
      doc.addPage();
      yPosition = margin;
      return true;
    }
    return false;
  };

  // Helper function to wrap text
  const wrapText = (text: string, maxWidth: number): string[] => {
    return doc.splitTextToSize(text, maxWidth);
  };

  // Title
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  const titleLines = wrapText(data.title, contentWidth);
  titleLines.forEach((line) => {
    checkPageBreak(10);
    doc.text(line, margin, yPosition);
    yPosition += 10;
  });
  yPosition += 5;

  // Metadata section
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 100, 100);

  const metadata: string[] = [];
  metadata.push(`Date: ${data.createdAt.toLocaleString()}`);
  if (data.sentinelName) metadata.push(`Sentinel: ${data.sentinelName}`);
  if (data.modelName) metadata.push(`Model: ${data.modelName}`);
  if (data.totalTokens) metadata.push(`Tokens: ${data.totalTokens.toLocaleString()}`);
  if (data.totalCost) metadata.push(`Cost: $${data.totalCost.toFixed(4)}`);

  metadata.forEach((line) => {
    checkPageBreak(5);
    doc.text(line, margin, yPosition);
    yPosition += 5;
  });
  yPosition += 10;

  // Separator line
  doc.setDrawColor(200, 200, 200);
  doc.line(margin, yPosition, pageWidth - margin, yPosition);
  yPosition += 10;

  // Messages
  doc.setTextColor(0, 0, 0);

  for (const message of data.messages) {
    checkPageBreak(20);

    // Message header (role)
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    
    if (message.role === "user") {
      doc.setTextColor(59, 130, 246); // Blue for user
      doc.text("You", margin, yPosition);
    } else {
      doc.setTextColor(16, 185, 129); // Green for AI
      doc.text(data.sentinelName || "AI", margin, yPosition);
    }
    yPosition += 7;

    // Message content
    doc.setFont("helvetica", "normal");
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(10);

    // Clean markdown formatting (basic cleanup)
    let cleanContent = message.content
      .replace(/\*\*(.*?)\*\*/g, "$1") // Remove bold
      .replace(/\*(.*?)\*/g, "$1") // Remove italic
      .replace(/`(.*?)`/g, "$1") // Remove inline code
      .replace(/^#+\s/gm, "") // Remove headers
      .replace(/^[-*]\s/gm, "• "); // Convert lists to bullets

    const contentLines = wrapText(cleanContent, contentWidth);
    contentLines.forEach((line) => {
      checkPageBreak(5);
      doc.text(line, margin, yPosition);
      yPosition += 5;
    });

    yPosition += 8; // Space between messages

    // Add light separator between messages
    doc.setDrawColor(240, 240, 240);
    doc.line(margin, yPosition, pageWidth - margin, yPosition);
    yPosition += 8;
  }

  // Footer on last page
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.setFont("helvetica", "normal");
    doc.text(
      `Page ${i} of ${totalPages}`,
      pageWidth / 2,
      pageHeight - 10,
      { align: "center" }
    );
    doc.text(
      "Generated by Sovereign AI Assistant",
      pageWidth / 2,
      pageHeight - 5,
      { align: "center" }
    );
  }

  // Convert to buffer
  const pdfBuffer = Buffer.from(doc.output("arraybuffer"));
  return pdfBuffer;
}
